# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CanvasDataXform(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'pivot': 'Vector3',
        'rotate': 'Vector3',
        'scale': 'Vector3',
        'translate': 'Vector3'
    }

    attribute_map = {
        'pivot': 'pivot',
        'rotate': 'rotate',
        'scale': 'scale',
        'translate': 'translate'
    }

    def __init__(self, pivot=None, rotate=None, scale=None, translate=None):  # noqa: E501
        """CanvasDataXform - a model defined in Swagger"""  # noqa: E501
        self._pivot = None
        self._rotate = None
        self._scale = None
        self._translate = None
        self.discriminator = None
        if pivot is not None:
            self.pivot = pivot
        if rotate is not None:
            self.rotate = rotate
        if scale is not None:
            self.scale = scale
        if translate is not None:
            self.translate = translate

    @property
    def pivot(self):
        """Gets the pivot of this CanvasDataXform.  # noqa: E501


        :return: The pivot of this CanvasDataXform.  # noqa: E501
        :rtype: Vector3
        """
        return self._pivot

    @pivot.setter
    def pivot(self, pivot):
        """Sets the pivot of this CanvasDataXform.


        :param pivot: The pivot of this CanvasDataXform.  # noqa: E501
        :type: Vector3
        """

        self._pivot = pivot

    @property
    def rotate(self):
        """Gets the rotate of this CanvasDataXform.  # noqa: E501


        :return: The rotate of this CanvasDataXform.  # noqa: E501
        :rtype: Vector3
        """
        return self._rotate

    @rotate.setter
    def rotate(self, rotate):
        """Sets the rotate of this CanvasDataXform.


        :param rotate: The rotate of this CanvasDataXform.  # noqa: E501
        :type: Vector3
        """

        self._rotate = rotate

    @property
    def scale(self):
        """Gets the scale of this CanvasDataXform.  # noqa: E501


        :return: The scale of this CanvasDataXform.  # noqa: E501
        :rtype: Vector3
        """
        return self._scale

    @scale.setter
    def scale(self, scale):
        """Sets the scale of this CanvasDataXform.


        :param scale: The scale of this CanvasDataXform.  # noqa: E501
        :type: Vector3
        """

        self._scale = scale

    @property
    def translate(self):
        """Gets the translate of this CanvasDataXform.  # noqa: E501


        :return: The translate of this CanvasDataXform.  # noqa: E501
        :rtype: Vector3
        """
        return self._translate

    @translate.setter
    def translate(self, translate):
        """Sets the translate of this CanvasDataXform.


        :param translate: The translate of this CanvasDataXform.  # noqa: E501
        :type: Vector3
        """

        self._translate = translate

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CanvasDataXform, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CanvasDataXform):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
