# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ControlData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'type': 'str',
        'value': 'OneOfcontrolDataValue'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'type': 'type',
        'value': 'value'
    }

    def __init__(self, id=None, name=None, type=None, value=None):  # noqa: E501
        """ControlData - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._type = None
        self._value = None
        self.discriminator = None
        self.id = id
        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        self.value = value

    @property
    def id(self):
        """Gets the id of this ControlData.  # noqa: E501

        Unique identifier of the control (readonly)  # noqa: E501

        :return: The id of this ControlData.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this ControlData.

        Unique identifier of the control (readonly)  # noqa: E501

        :param id: The id of this ControlData.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this ControlData.  # noqa: E501

        Name of the control  # noqa: E501

        :return: The name of this ControlData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ControlData.

        Name of the control  # noqa: E501

        :param name: The name of this ControlData.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this ControlData.  # noqa: E501

        Type of the control - 'Option', 'Text', 'Boolean', etc. (readonly)  # noqa: E501

        :return: The type of this ControlData.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this ControlData.

        Type of the control - 'Option', 'Text', 'Boolean', etc. (readonly)  # noqa: E501

        :param type: The type of this ControlData.  # noqa: E501
        :type: str
        """
        allowed_values = ["Option", "Text", "MText", "Boolean", "Numeric", "Color", "Menu"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def value(self):
        """Gets the value of this ControlData.  # noqa: E501

        Value of the control (string representation for all types)  # noqa: E501

        :return: The value of this ControlData.  # noqa: E501
        :rtype: OneOfcontrolDataValue
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this ControlData.

        Value of the control (string representation for all types)  # noqa: E501

        :param value: The value of this ControlData.  # noqa: E501
        :type: OneOfcontrolDataValue
        """
        if value is None:
            raise ValueError("Invalid value for `value`, must not be `None`")  # noqa: E501

        self._value = value

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ControlData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ControlData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
