# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class FillDataOrientation(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'rot': 'float',
        'sx': 'float',
        'sy': 'float',
        'tx': 'float',
        'ty': 'float'
    }

    attribute_map = {
        'rot': 'rot',
        'sx': 'sx',
        'sy': 'sy',
        'tx': 'tx',
        'ty': 'ty'
    }

    def __init__(self, rot=None, sx=None, sy=None, tx=None, ty=None):  # noqa: E501
        """FillDataOrientation - a model defined in Swagger"""  # noqa: E501
        self._rot = None
        self._sx = None
        self._sy = None
        self._tx = None
        self._ty = None
        self.discriminator = None
        if rot is not None:
            self.rot = rot
        if sx is not None:
            self.sx = sx
        if sy is not None:
            self.sy = sy
        if tx is not None:
            self.tx = tx
        if ty is not None:
            self.ty = ty

    @property
    def rot(self):
        """Gets the rot of this FillDataOrientation.  # noqa: E501

        Rotation angle of the fill in degrees  # noqa: E501

        :return: The rot of this FillDataOrientation.  # noqa: E501
        :rtype: float
        """
        return self._rot

    @rot.setter
    def rot(self, rot):
        """Sets the rot of this FillDataOrientation.

        Rotation angle of the fill in degrees  # noqa: E501

        :param rot: The rot of this FillDataOrientation.  # noqa: E501
        :type: float
        """

        self._rot = rot

    @property
    def sx(self):
        """Gets the sx of this FillDataOrientation.  # noqa: E501

        Horizontal scale of the fill  # noqa: E501

        :return: The sx of this FillDataOrientation.  # noqa: E501
        :rtype: float
        """
        return self._sx

    @sx.setter
    def sx(self, sx):
        """Sets the sx of this FillDataOrientation.

        Horizontal scale of the fill  # noqa: E501

        :param sx: The sx of this FillDataOrientation.  # noqa: E501
        :type: float
        """

        self._sx = sx

    @property
    def sy(self):
        """Gets the sy of this FillDataOrientation.  # noqa: E501

        Vertical scale of the fill  # noqa: E501

        :return: The sy of this FillDataOrientation.  # noqa: E501
        :rtype: float
        """
        return self._sy

    @sy.setter
    def sy(self, sy):
        """Sets the sy of this FillDataOrientation.

        Vertical scale of the fill  # noqa: E501

        :param sy: The sy of this FillDataOrientation.  # noqa: E501
        :type: float
        """

        self._sy = sy

    @property
    def tx(self):
        """Gets the tx of this FillDataOrientation.  # noqa: E501

        Horizontal translation of the fill  # noqa: E501

        :return: The tx of this FillDataOrientation.  # noqa: E501
        :rtype: float
        """
        return self._tx

    @tx.setter
    def tx(self, tx):
        """Sets the tx of this FillDataOrientation.

        Horizontal translation of the fill  # noqa: E501

        :param tx: The tx of this FillDataOrientation.  # noqa: E501
        :type: float
        """

        self._tx = tx

    @property
    def ty(self):
        """Gets the ty of this FillDataOrientation.  # noqa: E501

        Vertical translation of the fill  # noqa: E501

        :return: The ty of this FillDataOrientation.  # noqa: E501
        :rtype: float
        """
        return self._ty

    @ty.setter
    def ty(self, ty):
        """Sets the ty of this FillDataOrientation.

        Vertical translation of the fill  # noqa: E501

        :param ty: The ty of this FillDataOrientation.  # noqa: E501
        :type: float
        """

        self._ty = ty

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(FillDataOrientation, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FillDataOrientation):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
