# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class LayerData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'active': 'bool',
        'recursive': 'bool',
        'group': 'bool',
        'parent': 'int',
        'colorgrade': 'ColorgradeData',
        'canvas': 'CanvasData',
        'fill': 'FillData',
        'matte': 'MatteData'
    }

    attribute_map = {
        'name': 'name',
        'active': 'active',
        'recursive': 'recursive',
        'group': 'group',
        'parent': 'parent',
        'colorgrade': 'colorgrade',
        'canvas': 'canvas',
        'fill': 'fill',
        'matte': 'matte'
    }

    def __init__(self, name=None, active=None, recursive=None, group=None, parent=None, colorgrade=None, canvas=None, fill=None, matte=None):  # noqa: E501
        """LayerData - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._active = None
        self._recursive = None
        self._group = None
        self._parent = None
        self._colorgrade = None
        self._canvas = None
        self._fill = None
        self._matte = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if active is not None:
            self.active = active
        if recursive is not None:
            self.recursive = recursive
        if group is not None:
            self.group = group
        if parent is not None:
            self.parent = parent
        if colorgrade is not None:
            self.colorgrade = colorgrade
        if canvas is not None:
            self.canvas = canvas
        if fill is not None:
            self.fill = fill
        if matte is not None:
            self.matte = matte

    @property
    def name(self):
        """Gets the name of this LayerData.  # noqa: E501

        Name of the layer  # noqa: E501

        :return: The name of this LayerData.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this LayerData.

        Name of the layer  # noqa: E501

        :param name: The name of this LayerData.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def active(self):
        """Gets the active of this LayerData.  # noqa: E501

        Is the layer active  # noqa: E501

        :return: The active of this LayerData.  # noqa: E501
        :rtype: bool
        """
        return self._active

    @active.setter
    def active(self, active):
        """Sets the active of this LayerData.

        Is the layer active  # noqa: E501

        :param active: The active of this LayerData.  # noqa: E501
        :type: bool
        """

        self._active = active

    @property
    def recursive(self):
        """Gets the recursive of this LayerData.  # noqa: E501

        Whether the layer settings are applied recursively to all layers below in the stack  # noqa: E501

        :return: The recursive of this LayerData.  # noqa: E501
        :rtype: bool
        """
        return self._recursive

    @recursive.setter
    def recursive(self, recursive):
        """Sets the recursive of this LayerData.

        Whether the layer settings are applied recursively to all layers below in the stack  # noqa: E501

        :param recursive: The recursive of this LayerData.  # noqa: E501
        :type: bool
        """

        self._recursive = recursive

    @property
    def group(self):
        """Gets the group of this LayerData.  # noqa: E501

        Whether the layer is a group layer containing sub-layers  # noqa: E501

        :return: The group of this LayerData.  # noqa: E501
        :rtype: bool
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this LayerData.

        Whether the layer is a group layer containing sub-layers  # noqa: E501

        :param group: The group of this LayerData.  # noqa: E501
        :type: bool
        """

        self._group = group

    @property
    def parent(self):
        """Gets the parent of this LayerData.  # noqa: E501

        Index of the parent layer.  # noqa: E501

        :return: The parent of this LayerData.  # noqa: E501
        :rtype: int
        """
        return self._parent

    @parent.setter
    def parent(self, parent):
        """Sets the parent of this LayerData.

        Index of the parent layer.  # noqa: E501

        :param parent: The parent of this LayerData.  # noqa: E501
        :type: int
        """

        self._parent = parent

    @property
    def colorgrade(self):
        """Gets the colorgrade of this LayerData.  # noqa: E501


        :return: The colorgrade of this LayerData.  # noqa: E501
        :rtype: ColorgradeData
        """
        return self._colorgrade

    @colorgrade.setter
    def colorgrade(self, colorgrade):
        """Sets the colorgrade of this LayerData.


        :param colorgrade: The colorgrade of this LayerData.  # noqa: E501
        :type: ColorgradeData
        """

        self._colorgrade = colorgrade

    @property
    def canvas(self):
        """Gets the canvas of this LayerData.  # noqa: E501


        :return: The canvas of this LayerData.  # noqa: E501
        :rtype: CanvasData
        """
        return self._canvas

    @canvas.setter
    def canvas(self, canvas):
        """Sets the canvas of this LayerData.


        :param canvas: The canvas of this LayerData.  # noqa: E501
        :type: CanvasData
        """

        self._canvas = canvas

    @property
    def fill(self):
        """Gets the fill of this LayerData.  # noqa: E501


        :return: The fill of this LayerData.  # noqa: E501
        :rtype: FillData
        """
        return self._fill

    @fill.setter
    def fill(self, fill):
        """Sets the fill of this LayerData.


        :param fill: The fill of this LayerData.  # noqa: E501
        :type: FillData
        """

        self._fill = fill

    @property
    def matte(self):
        """Gets the matte of this LayerData.  # noqa: E501


        :return: The matte of this LayerData.  # noqa: E501
        :rtype: MatteData
        """
        return self._matte

    @matte.setter
    def matte(self, matte):
        """Sets the matte of this LayerData.


        :param matte: The matte of this LayerData.  # noqa: E501
        :type: MatteData
        """

        self._matte = matte

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(LayerData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, LayerData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
