# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MatteData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'shot_uuid': 'Uuid',
        'blend_mode': 'str',
        'blur': 'float',
        'blur_angle': 'float',
        'blur_dir_active': 'bool',
        'channel_mask': 'MatteDataChannelMask',
        'map': 'str',
        'slip': 'float',
        'orientation': 'MatteDataOrientation',
        'warp': 'str',
        'warp_blur_filter': 'float',
        'warp_equi_dist': 'float'
    }

    attribute_map = {
        'shot_uuid': 'shot_uuid',
        'blend_mode': 'blend_mode',
        'blur': 'blur',
        'blur_angle': 'blur_angle',
        'blur_dir_active': 'blur_dir_active',
        'channel_mask': 'channel_mask',
        'map': 'map',
        'slip': 'slip',
        'orientation': 'orientation',
        'warp': 'warp',
        'warp_blur_filter': 'warp_blur_filter',
        'warp_equi_dist': 'warp_equi_dist'
    }

    def __init__(self, shot_uuid=None, blend_mode=None, blur=None, blur_angle=None, blur_dir_active=None, channel_mask=None, map=None, slip=None, orientation=None, warp=None, warp_blur_filter=None, warp_equi_dist=None):  # noqa: E501
        """MatteData - a model defined in Swagger"""  # noqa: E501
        self._shot_uuid = None
        self._blend_mode = None
        self._blur = None
        self._blur_angle = None
        self._blur_dir_active = None
        self._channel_mask = None
        self._map = None
        self._slip = None
        self._orientation = None
        self._warp = None
        self._warp_blur_filter = None
        self._warp_equi_dist = None
        self.discriminator = None
        if shot_uuid is not None:
            self.shot_uuid = shot_uuid
        if blend_mode is not None:
            self.blend_mode = blend_mode
        if blur is not None:
            self.blur = blur
        if blur_angle is not None:
            self.blur_angle = blur_angle
        if blur_dir_active is not None:
            self.blur_dir_active = blur_dir_active
        if channel_mask is not None:
            self.channel_mask = channel_mask
        if map is not None:
            self.map = map
        if slip is not None:
            self.slip = slip
        if orientation is not None:
            self.orientation = orientation
        if warp is not None:
            self.warp = warp
        if warp_blur_filter is not None:
            self.warp_blur_filter = warp_blur_filter
        if warp_equi_dist is not None:
            self.warp_equi_dist = warp_equi_dist

    @property
    def shot_uuid(self):
        """Gets the shot_uuid of this MatteData.  # noqa: E501


        :return: The shot_uuid of this MatteData.  # noqa: E501
        :rtype: Uuid
        """
        return self._shot_uuid

    @shot_uuid.setter
    def shot_uuid(self, shot_uuid):
        """Sets the shot_uuid of this MatteData.


        :param shot_uuid: The shot_uuid of this MatteData.  # noqa: E501
        :type: Uuid
        """

        self._shot_uuid = shot_uuid

    @property
    def blend_mode(self):
        """Gets the blend_mode of this MatteData.  # noqa: E501

        Blend mode of the matte  # noqa: E501

        :return: The blend_mode of this MatteData.  # noqa: E501
        :rtype: str
        """
        return self._blend_mode

    @blend_mode.setter
    def blend_mode(self, blend_mode):
        """Sets the blend_mode of this MatteData.

        Blend mode of the matte  # noqa: E501

        :param blend_mode: The blend_mode of this MatteData.  # noqa: E501
        :type: str
        """
        allowed_values = ["None", "Over", "Add", "Subtract", "Copy"]  # noqa: E501
        if blend_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `blend_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(blend_mode, allowed_values)
            )

        self._blend_mode = blend_mode

    @property
    def blur(self):
        """Gets the blur of this MatteData.  # noqa: E501

        Amount of blur to apply to the matte  # noqa: E501

        :return: The blur of this MatteData.  # noqa: E501
        :rtype: float
        """
        return self._blur

    @blur.setter
    def blur(self, blur):
        """Sets the blur of this MatteData.

        Amount of blur to apply to the matte  # noqa: E501

        :param blur: The blur of this MatteData.  # noqa: E501
        :type: float
        """

        self._blur = blur

    @property
    def blur_angle(self):
        """Gets the blur_angle of this MatteData.  # noqa: E501

        Angle of the blur to apply to the matte  # noqa: E501

        :return: The blur_angle of this MatteData.  # noqa: E501
        :rtype: float
        """
        return self._blur_angle

    @blur_angle.setter
    def blur_angle(self, blur_angle):
        """Sets the blur_angle of this MatteData.

        Angle of the blur to apply to the matte  # noqa: E501

        :param blur_angle: The blur_angle of this MatteData.  # noqa: E501
        :type: float
        """

        self._blur_angle = blur_angle

    @property
    def blur_dir_active(self):
        """Gets the blur_dir_active of this MatteData.  # noqa: E501

        Whether the blur direction is active for the matte  # noqa: E501

        :return: The blur_dir_active of this MatteData.  # noqa: E501
        :rtype: bool
        """
        return self._blur_dir_active

    @blur_dir_active.setter
    def blur_dir_active(self, blur_dir_active):
        """Sets the blur_dir_active of this MatteData.

        Whether the blur direction is active for the matte  # noqa: E501

        :param blur_dir_active: The blur_dir_active of this MatteData.  # noqa: E501
        :type: bool
        """

        self._blur_dir_active = blur_dir_active

    @property
    def channel_mask(self):
        """Gets the channel_mask of this MatteData.  # noqa: E501


        :return: The channel_mask of this MatteData.  # noqa: E501
        :rtype: MatteDataChannelMask
        """
        return self._channel_mask

    @channel_mask.setter
    def channel_mask(self, channel_mask):
        """Sets the channel_mask of this MatteData.


        :param channel_mask: The channel_mask of this MatteData.  # noqa: E501
        :type: MatteDataChannelMask
        """

        self._channel_mask = channel_mask

    @property
    def map(self):
        """Gets the map of this MatteData.  # noqa: E501

        Map file path for the matte  # noqa: E501

        :return: The map of this MatteData.  # noqa: E501
        :rtype: str
        """
        return self._map

    @map.setter
    def map(self, map):
        """Sets the map of this MatteData.

        Map file path for the matte  # noqa: E501

        :param map: The map of this MatteData.  # noqa: E501
        :type: str
        """
        allowed_values = ["Projected", "On Canvas", "Pinned"]  # noqa: E501
        if map not in allowed_values:
            raise ValueError(
                "Invalid value for `map` ({0}), must be one of {1}"  # noqa: E501
                .format(map, allowed_values)
            )

        self._map = map

    @property
    def slip(self):
        """Gets the slip of this MatteData.  # noqa: E501

        Slip in frames of the matte  # noqa: E501

        :return: The slip of this MatteData.  # noqa: E501
        :rtype: float
        """
        return self._slip

    @slip.setter
    def slip(self, slip):
        """Sets the slip of this MatteData.

        Slip in frames of the matte  # noqa: E501

        :param slip: The slip of this MatteData.  # noqa: E501
        :type: float
        """

        self._slip = slip

    @property
    def orientation(self):
        """Gets the orientation of this MatteData.  # noqa: E501


        :return: The orientation of this MatteData.  # noqa: E501
        :rtype: MatteDataOrientation
        """
        return self._orientation

    @orientation.setter
    def orientation(self, orientation):
        """Sets the orientation of this MatteData.


        :param orientation: The orientation of this MatteData.  # noqa: E501
        :type: MatteDataOrientation
        """

        self._orientation = orientation

    @property
    def warp(self):
        """Gets the warp of this MatteData.  # noqa: E501

        Warp type of the matte  # noqa: E501

        :return: The warp of this MatteData.  # noqa: E501
        :rtype: str
        """
        return self._warp

    @warp.setter
    def warp(self, warp):
        """Sets the warp of this MatteData.

        Warp type of the matte  # noqa: E501

        :param warp: The warp of this MatteData.  # noqa: E501
        :type: str
        """
        allowed_values = ["None", "Equi360", "Equi180"]  # noqa: E501
        if warp not in allowed_values:
            raise ValueError(
                "Invalid value for `warp` ({0}), must be one of {1}"  # noqa: E501
                .format(warp, allowed_values)
            )

        self._warp = warp

    @property
    def warp_blur_filter(self):
        """Gets the warp_blur_filter of this MatteData.  # noqa: E501

        Warp blur filter  # noqa: E501

        :return: The warp_blur_filter of this MatteData.  # noqa: E501
        :rtype: float
        """
        return self._warp_blur_filter

    @warp_blur_filter.setter
    def warp_blur_filter(self, warp_blur_filter):
        """Sets the warp_blur_filter of this MatteData.

        Warp blur filter  # noqa: E501

        :param warp_blur_filter: The warp_blur_filter of this MatteData.  # noqa: E501
        :type: float
        """

        self._warp_blur_filter = warp_blur_filter

    @property
    def warp_equi_dist(self):
        """Gets the warp_equi_dist of this MatteData.  # noqa: E501

        Warp equi distance  # noqa: E501

        :return: The warp_equi_dist of this MatteData.  # noqa: E501
        :rtype: float
        """
        return self._warp_equi_dist

    @warp_equi_dist.setter
    def warp_equi_dist(self, warp_equi_dist):
        """Sets the warp_equi_dist of this MatteData.

        Warp equi distance  # noqa: E501

        :param warp_equi_dist: The warp_equi_dist of this MatteData.  # noqa: E501
        :type: float
        """

        self._warp_equi_dist = warp_equi_dist

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MatteData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MatteData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
