# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class MoveLayerData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'group_index': 'int',
        'position_index': 'int'
    }

    attribute_map = {
        'group_index': 'group_index',
        'position_index': 'position_index'
    }

    def __init__(self, group_index=None, position_index=None):  # noqa: E501
        """MoveLayerData - a model defined in Swagger"""  # noqa: E501
        self._group_index = None
        self._position_index = None
        self.discriminator = None
        if group_index is not None:
            self.group_index = group_index
        if position_index is not None:
            self.position_index = position_index

    @property
    def group_index(self):
        """Gets the group_index of this MoveLayerData.  # noqa: E501

        Move current layer into a exist group with group_index in the layer stack. Group 0 is the root of the layer stack  # noqa: E501

        :return: The group_index of this MoveLayerData.  # noqa: E501
        :rtype: int
        """
        return self._group_index

    @group_index.setter
    def group_index(self, group_index):
        """Sets the group_index of this MoveLayerData.

        Move current layer into a exist group with group_index in the layer stack. Group 0 is the root of the layer stack  # noqa: E501

        :param group_index: The group_index of this MoveLayerData.  # noqa: E501
        :type: int
        """

        self._group_index = group_index

    @property
    def position_index(self):
        """Gets the position_index of this MoveLayerData.  # noqa: E501

        Move the current layer to position_index at the specified group level.  # noqa: E501

        :return: The position_index of this MoveLayerData.  # noqa: E501
        :rtype: int
        """
        return self._position_index

    @position_index.setter
    def position_index(self, position_index):
        """Sets the position_index of this MoveLayerData.

        Move the current layer to position_index at the specified group level.  # noqa: E501

        :param position_index: The position_index of this MoveLayerData.  # noqa: E501
        :type: int
        """

        self._position_index = position_index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MoveLayerData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MoveLayerData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
