# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class ReferenceShotData(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ref_uuid': 'Uuid',
        'ref_slip': 'float'
    }

    attribute_map = {
        'ref_uuid': 'ref_uuid',
        'ref_slip': 'ref_slip'
    }

    def __init__(self, ref_uuid=None, ref_slip=None):  # noqa: E501
        """ReferenceShotData - a model defined in Swagger"""  # noqa: E501
        self._ref_uuid = None
        self._ref_slip = None
        self.discriminator = None
        if ref_uuid is not None:
            self.ref_uuid = ref_uuid
        if ref_slip is not None:
            self.ref_slip = ref_slip

    @property
    def ref_uuid(self):
        """Gets the ref_uuid of this ReferenceShotData.  # noqa: E501


        :return: The ref_uuid of this ReferenceShotData.  # noqa: E501
        :rtype: Uuid
        """
        return self._ref_uuid

    @ref_uuid.setter
    def ref_uuid(self, ref_uuid):
        """Sets the ref_uuid of this ReferenceShotData.


        :param ref_uuid: The ref_uuid of this ReferenceShotData.  # noqa: E501
        :type: Uuid
        """

        self._ref_uuid = ref_uuid

    @property
    def ref_slip(self):
        """Gets the ref_slip of this ReferenceShotData.  # noqa: E501

        Slip, in frames, of the reference Shot with the timeline  # noqa: E501

        :return: The ref_slip of this ReferenceShotData.  # noqa: E501
        :rtype: float
        """
        return self._ref_slip

    @ref_slip.setter
    def ref_slip(self, ref_slip):
        """Sets the ref_slip of this ReferenceShotData.

        Slip, in frames, of the reference Shot with the timeline  # noqa: E501

        :param ref_slip: The ref_slip of this ReferenceShotData.  # noqa: E501
        :type: float
        """

        self._ref_slip = ref_slip

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ReferenceShotData, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ReferenceShotData):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
