# coding: utf-8

"""
    Assimilate REST API

    REST API for the Assimilate Product Suite software.   # noqa: E501

    OpenAPI spec version: 1.0.5
    Contact: support@assimilateinc.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class RenderQueueItem(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'uuid': 'Uuid',
        'name': 'str',
        'cdate': 'str',
        'format': 'str',
        'range_in': 'int',
        'range_out': 'int',
        'range_txt': 'str',
        'path': 'str',
        'group': 'str',
        'status': 'str',
        'time_processed': 'int',
        'time_left': 'int',
        'time_total': 'int',
        'frames_done': 'int',
        'frames_left': 'int',
        'frames_total': 'int',
        'output_uuid': 'Uuid'
    }

    attribute_map = {
        'uuid': 'uuid',
        'name': 'name',
        'cdate': 'cdate',
        'format': 'format',
        'range_in': 'range_in',
        'range_out': 'range_out',
        'range_txt': 'range_txt',
        'path': 'path',
        'group': 'group',
        'status': 'status',
        'time_processed': 'time_processed',
        'time_left': 'time_left',
        'time_total': 'time_total',
        'frames_done': 'frames_done',
        'frames_left': 'frames_left',
        'frames_total': 'frames_total',
        'output_uuid': 'output_uuid'
    }

    def __init__(self, uuid=None, name=None, cdate=None, format=None, range_in=None, range_out=None, range_txt=None, path=None, group=None, status=None, time_processed=None, time_left=None, time_total=None, frames_done=None, frames_left=None, frames_total=None, output_uuid=None):  # noqa: E501
        """RenderQueueItem - a model defined in Swagger"""  # noqa: E501
        self._uuid = None
        self._name = None
        self._cdate = None
        self._format = None
        self._range_in = None
        self._range_out = None
        self._range_txt = None
        self._path = None
        self._group = None
        self._status = None
        self._time_processed = None
        self._time_left = None
        self._time_total = None
        self._frames_done = None
        self._frames_left = None
        self._frames_total = None
        self._output_uuid = None
        self.discriminator = None
        if uuid is not None:
            self.uuid = uuid
        if name is not None:
            self.name = name
        if cdate is not None:
            self.cdate = cdate
        if format is not None:
            self.format = format
        if range_in is not None:
            self.range_in = range_in
        if range_out is not None:
            self.range_out = range_out
        if range_txt is not None:
            self.range_txt = range_txt
        if path is not None:
            self.path = path
        if group is not None:
            self.group = group
        if status is not None:
            self.status = status
        if time_processed is not None:
            self.time_processed = time_processed
        if time_left is not None:
            self.time_left = time_left
        if time_total is not None:
            self.time_total = time_total
        if frames_done is not None:
            self.frames_done = frames_done
        if frames_left is not None:
            self.frames_left = frames_left
        if frames_total is not None:
            self.frames_total = frames_total
        if output_uuid is not None:
            self.output_uuid = output_uuid

    @property
    def uuid(self):
        """Gets the uuid of this RenderQueueItem.  # noqa: E501


        :return: The uuid of this RenderQueueItem.  # noqa: E501
        :rtype: Uuid
        """
        return self._uuid

    @uuid.setter
    def uuid(self, uuid):
        """Sets the uuid of this RenderQueueItem.


        :param uuid: The uuid of this RenderQueueItem.  # noqa: E501
        :type: Uuid
        """

        self._uuid = uuid

    @property
    def name(self):
        """Gets the name of this RenderQueueItem.  # noqa: E501

        Name of the render Queu Item  # noqa: E501

        :return: The name of this RenderQueueItem.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this RenderQueueItem.

        Name of the render Queu Item  # noqa: E501

        :param name: The name of this RenderQueueItem.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def cdate(self):
        """Gets the cdate of this RenderQueueItem.  # noqa: E501

        Date the render Queu Item was created  # noqa: E501

        :return: The cdate of this RenderQueueItem.  # noqa: E501
        :rtype: str
        """
        return self._cdate

    @cdate.setter
    def cdate(self, cdate):
        """Sets the cdate of this RenderQueueItem.

        Date the render Queu Item was created  # noqa: E501

        :param cdate: The cdate of this RenderQueueItem.  # noqa: E501
        :type: str
        """

        self._cdate = cdate

    @property
    def format(self):
        """Gets the format of this RenderQueueItem.  # noqa: E501


        :return: The format of this RenderQueueItem.  # noqa: E501
        :rtype: str
        """
        return self._format

    @format.setter
    def format(self, format):
        """Sets the format of this RenderQueueItem.


        :param format: The format of this RenderQueueItem.  # noqa: E501
        :type: str
        """

        self._format = format

    @property
    def range_in(self):
        """Gets the range_in of this RenderQueueItem.  # noqa: E501

        Frame In  # noqa: E501

        :return: The range_in of this RenderQueueItem.  # noqa: E501
        :rtype: int
        """
        return self._range_in

    @range_in.setter
    def range_in(self, range_in):
        """Sets the range_in of this RenderQueueItem.

        Frame In  # noqa: E501

        :param range_in: The range_in of this RenderQueueItem.  # noqa: E501
        :type: int
        """

        self._range_in = range_in

    @property
    def range_out(self):
        """Gets the range_out of this RenderQueueItem.  # noqa: E501

        Frame Out  # noqa: E501

        :return: The range_out of this RenderQueueItem.  # noqa: E501
        :rtype: int
        """
        return self._range_out

    @range_out.setter
    def range_out(self, range_out):
        """Sets the range_out of this RenderQueueItem.

        Frame Out  # noqa: E501

        :param range_out: The range_out of this RenderQueueItem.  # noqa: E501
        :type: int
        """

        self._range_out = range_out

    @property
    def range_txt(self):
        """Gets the range_txt of this RenderQueueItem.  # noqa: E501

        Frame range  # noqa: E501

        :return: The range_txt of this RenderQueueItem.  # noqa: E501
        :rtype: str
        """
        return self._range_txt

    @range_txt.setter
    def range_txt(self, range_txt):
        """Sets the range_txt of this RenderQueueItem.

        Frame range  # noqa: E501

        :param range_txt: The range_txt of this RenderQueueItem.  # noqa: E501
        :type: str
        """

        self._range_txt = range_txt

    @property
    def path(self):
        """Gets the path of this RenderQueueItem.  # noqa: E501

        Output path  # noqa: E501

        :return: The path of this RenderQueueItem.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this RenderQueueItem.

        Output path  # noqa: E501

        :param path: The path of this RenderQueueItem.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def group(self):
        """Gets the group of this RenderQueueItem.  # noqa: E501

        Name of the group the render job belongs to  # noqa: E501

        :return: The group of this RenderQueueItem.  # noqa: E501
        :rtype: str
        """
        return self._group

    @group.setter
    def group(self, group):
        """Sets the group of this RenderQueueItem.

        Name of the group the render job belongs to  # noqa: E501

        :param group: The group of this RenderQueueItem.  # noqa: E501
        :type: str
        """

        self._group = group

    @property
    def status(self):
        """Gets the status of this RenderQueueItem.  # noqa: E501

        Status of the render job  # noqa: E501

        :return: The status of this RenderQueueItem.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this RenderQueueItem.

        Status of the render job  # noqa: E501

        :param status: The status of this RenderQueueItem.  # noqa: E501
        :type: str
        """

        self._status = status

    @property
    def time_processed(self):
        """Gets the time_processed of this RenderQueueItem.  # noqa: E501

        Time processed in seconds  # noqa: E501

        :return: The time_processed of this RenderQueueItem.  # noqa: E501
        :rtype: int
        """
        return self._time_processed

    @time_processed.setter
    def time_processed(self, time_processed):
        """Sets the time_processed of this RenderQueueItem.

        Time processed in seconds  # noqa: E501

        :param time_processed: The time_processed of this RenderQueueItem.  # noqa: E501
        :type: int
        """

        self._time_processed = time_processed

    @property
    def time_left(self):
        """Gets the time_left of this RenderQueueItem.  # noqa: E501

        Time left in seconds  # noqa: E501

        :return: The time_left of this RenderQueueItem.  # noqa: E501
        :rtype: int
        """
        return self._time_left

    @time_left.setter
    def time_left(self, time_left):
        """Sets the time_left of this RenderQueueItem.

        Time left in seconds  # noqa: E501

        :param time_left: The time_left of this RenderQueueItem.  # noqa: E501
        :type: int
        """

        self._time_left = time_left

    @property
    def time_total(self):
        """Gets the time_total of this RenderQueueItem.  # noqa: E501

        Total time in seconds  # noqa: E501

        :return: The time_total of this RenderQueueItem.  # noqa: E501
        :rtype: int
        """
        return self._time_total

    @time_total.setter
    def time_total(self, time_total):
        """Sets the time_total of this RenderQueueItem.

        Total time in seconds  # noqa: E501

        :param time_total: The time_total of this RenderQueueItem.  # noqa: E501
        :type: int
        """

        self._time_total = time_total

    @property
    def frames_done(self):
        """Gets the frames_done of this RenderQueueItem.  # noqa: E501

        Number of frames done  # noqa: E501

        :return: The frames_done of this RenderQueueItem.  # noqa: E501
        :rtype: int
        """
        return self._frames_done

    @frames_done.setter
    def frames_done(self, frames_done):
        """Sets the frames_done of this RenderQueueItem.

        Number of frames done  # noqa: E501

        :param frames_done: The frames_done of this RenderQueueItem.  # noqa: E501
        :type: int
        """

        self._frames_done = frames_done

    @property
    def frames_left(self):
        """Gets the frames_left of this RenderQueueItem.  # noqa: E501

        Number of frames left  # noqa: E501

        :return: The frames_left of this RenderQueueItem.  # noqa: E501
        :rtype: int
        """
        return self._frames_left

    @frames_left.setter
    def frames_left(self, frames_left):
        """Sets the frames_left of this RenderQueueItem.

        Number of frames left  # noqa: E501

        :param frames_left: The frames_left of this RenderQueueItem.  # noqa: E501
        :type: int
        """

        self._frames_left = frames_left

    @property
    def frames_total(self):
        """Gets the frames_total of this RenderQueueItem.  # noqa: E501

        Total number of frames  # noqa: E501

        :return: The frames_total of this RenderQueueItem.  # noqa: E501
        :rtype: int
        """
        return self._frames_total

    @frames_total.setter
    def frames_total(self, frames_total):
        """Sets the frames_total of this RenderQueueItem.

        Total number of frames  # noqa: E501

        :param frames_total: The frames_total of this RenderQueueItem.  # noqa: E501
        :type: int
        """

        self._frames_total = frames_total

    @property
    def output_uuid(self):
        """Gets the output_uuid of this RenderQueueItem.  # noqa: E501


        :return: The output_uuid of this RenderQueueItem.  # noqa: E501
        :rtype: Uuid
        """
        return self._output_uuid

    @output_uuid.setter
    def output_uuid(self, output_uuid):
        """Sets the output_uuid of this RenderQueueItem.


        :param output_uuid: The output_uuid of this RenderQueueItem.  # noqa: E501
        :type: Uuid
        """

        self._output_uuid = output_uuid

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(RenderQueueItem, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, RenderQueueItem):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
